### ISSUE TITLE
Android input method

### ISSUE THREAD

**Issue by onitake** [onitake/kanjirecog#3]
@SebiderSushi @afmachado

The master branch now contains an implementation of a custom keyboard aka input method aka IME.

I kept the minimum API level to 14 (i.e. Android 4.0, Ice Cream Sandwich), which should cover most devices on the market today.

What's still missing is:
- [ ] Translations (I added a few new strings, they need to be translated to Brazilian Portuguese)
- [ ] Better UX (the button sidebar is a bit annoying)
- [ ] Testing

Contributions are welcome!

**Comment by SebiderSushi** [comment]
Awesome. I just cloned the repository, built and installed this on my phone. I'll try to use it as much as possible in order to test. A few things i noticed right away:
- The behavior of the return button is more like a tab or down arrow key? It seems to navigate to other ui elements instead of entering newlines, which i think it's supposed to do, right?
- At least on my device running ResurrectionRemix 6.2.1 (based on Lineage 15.1), the UI outside of the drawing area (background of buttons, stroke counter and kanji suggestions) adapts to the application UI where the IME is displayed. This leads to situations like black text on black background or transparent background in situations where the text from the IME UI collides with the application UI behind, which also decreases readability.
Example apps where such behavior was problematic: Trebuchet 8.1.0 app drawer [transparent background] and F-Droid 1.7.1 app search [black background]

- Also, just now i thought that it could be very handy to support kana recognition as well, so that the keyboard can at least type every letter. Is this a lot more than a matter of simply adding the stroke data?

**Comment by onitake** [comment]
1. I assigned the `IME_ACTION_NEXT` to the "Return" button, as it is usually more useful than simply dismissing the keyboard. But this could be changed, obviously.
2. Can you post a screenshot of this behaviour? I think this is actually useful, but I can change the background of course. It shouldn't happen with the drawing area.
3. Not sure, but I may look into this later. Can you open a new issue? I want to focus on getting a basic IME ready first.

**Comment by onitake** [comment]
Issue 1. was fixed in b531d996aed2afe0dcbe092be16e6f28ae6ff635 - the "Return" button now triggers the "IME_ACTION_GO" action, which is more useful in dictionary apps. Perhaps the keyboard needs to be more context-aware here, but "GO" works better for me so far.

The keyboard is released and also available from F-Droid, and the other two findings have their own issues, so I'm going to close this issue here.
